events {
    worker_connections 1024;
}

http {
    server_tokens off;

    server {
        # скрытие версии nginx'а, 
        # чтобы было тяжелее злоумышленникам искать уязвимости
        listen 80;
        location / {
            proxy_pass http://backend:8080;

            # передача инфы о реальном клиенте 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # таймауты
            proxy_connect_timeout 5s;
            proxy_send_timeout 5s;
            proxy_read_timeout 5s;

        }
    }
}
